### ISSUE TITLE
并发上来之后，会出现too many open files;

### ISSUE THREAD

**Issue by water007melon** [lqqyt2423/go-mitmproxy#11]

**Comment by lqqyt2423** [comment]
https://github.com/lqqyt2423/go-mitmproxy/releases/tag/v0.1.5

**Comment by water007melon** [comment]
1

**Comment by water007melon** [comment]
更新之后效果不佳，打开文件数依然较多。

**Comment by lqqyt2423** [comment]
请发日志

**Comment by sayue2019** [comment]
@lqqyt2423 请问下作者，新版本这个问题解决了吗？项目中想用go-mitmproxy替换mitmproxy

**Comment by lqqyt2423** [comment]
我测试下来没啥问题

**Comment by sayue2019** [comment]
好的，那我就放心用了，感谢开源

**Comment by philipnimble** [comment]
hey :)
very cool repo!
Been testing your goproxy with https://github.com/maurice2k/ab-proxy with the following params:
sudo ./ab-proxy --show-errors -c 300 -n 4000 -X http://127.0.0.1:9080 https://9gag.com
first i got indeed "too many files open" error, then I ran  
```bash
sudo prlimit -n14096 -p PID
```
the result is the following:
```

Total initiated requests:     4000
   Completed requests:        4000
      HTTP-200 completed:     3754
      HTTP-501 completed:     246
   Failed requests:           0

```
and when checking the lsof of my proccess i get 3754 open sockets that won't close [lsof_out.txt](https://github.com/lqqyt2423/go-mitmproxy/files/8382032/lsof_out.txt)
I tried to add in helper.go in the transfer function this code
```golang
err := clientConn.SetDeadline(time.Now().Add(10 * time.Second))
if err != nil {
    LogErr(log, err)
}
err = serverConn.SetDeadline(time.Now().Add(10 * time.Second))
if err != nil {
    LogErr(log, err)
}
```
but it also did not help
any ideas? 
uname of the machine i'm trying this on :
```bash
Linux ip-172-26-12-143 4.19.0-14-cloud-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
```

**Comment by lqqyt2423** [comment]
@philipnimble

**Comment by lqqyt2423** [comment]
@philipnimble 
It seems the tcp connection between client (go-mitmproxy) and https endpoint (https://9gag.com) being alive, I guess you can try change client keepalive options in this area.
https://github.com/lqqyt2423/go-mitmproxy/blob/main/proxy/proxy.go#L49
Thanks for the test, I will follow your steps to test it by myself later.
