### ISSUE TITLE
expression is always true in if statement

### ISSUE THREAD

**Issue by philipnimble** [lqqyt2423/go-mitmproxy#15]
https://github.com/lqqyt2423/go-mitmproxy/blob/1cb5a375c0a6b22e8ce0d4ca56873fbbdf691ba5/proxy/middle.go#L144

```golang
buf[2] >= 0x0 || buf[2] <= 0x03
```
this expression is always true, what did you try to check there?

**Comment by lqqyt2423** [comment]
False when traffic is websocket.

**Comment by philipnimble** [comment]
(buf[2] >= 0x0 || buf[2] <= 0x03) but this is always true 
every number is always  **bigger than 0 or smaller than 3**

**Comment by lqqyt2423** [comment]
Already fixed it, thanks.

**Comment by lqqyt2423** [comment]
Already fixed it, thanks.
