### ISSUE TITLE
为什么其它请求都能正常代理,抖音就不行呢?

### ISSUE THREAD

**Issue by zhangya4548** [lqqyt2423/go-mitmproxy#16]
其它请求,qq,头条...都正常,但是抖音就不行

<img width="944" alt="image" src="https://user-images.githubusercontent.com/8876518/160399329-bc3d0c74-8def-4d46-a050-7f8b87edd339.png">

**Comment by lqqyt2423** [comment]
SSL Pinning

**Comment by zhangya4548** [comment]
这问题无解吗?

**Comment by mooncakedevop** [comment]
把证书改成系统证书？magisk应该有这个模块 move certficate

**Comment by Wowgreat** [comment]
改成系统证书还是不行
