### ISSUE TITLE
请问要关闭中间人和代理并且不退出程序在代码中应该怎么修改呢。

### ISSUE THREAD

**Issue by landd1897** [lqqyt2423/go-mitmproxy#24]
请问要关闭中间人和代理并且不退出程序在代码中应该怎么修改呢。

**Comment by landd1897** [comment]
以及可不可以对指定域名使用中间人代理呢

**Comment by anasbousselham** [comment]
像 ReqConditionFunc  ( goproxy )

**Comment by lqqyt2423** [comment]
> 请问要关闭中间人和代理并且不退出程序在代码中应该怎么修改呢。

https://github.com/lqqyt2423/go-mitmproxy/releases/tag/v1.3.0
add proxy.Close and proxy.Shutdown

**Comment by landd1897** [comment]
> 
大佬最棒啦！
