### ISSUE TITLE
是否考虑增加一个接口来动态切换上级代理呢？

### ISSUE THREAD

**Issue by candicandi** [lqqyt2423/go-mitmproxy#26]
如https://github.com/ouqiang/goproxy 这个一样，是否能增加一个接口来动态切换上级代理呢，如里面的ParentProxy(*http.Request) (*url.URL, error)

**Comment by lqqyt2423** [comment]
可通过环境变量设置代理
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890
