### ISSUE TITLE
单独部署到服务器上，作为代理服务器。会抓不到https请求，这个怎么处理。

### ISSUE THREAD

**Issue by libq** [lqqyt2423/go-mitmproxy#31]
1.我是将这个项目部署到服务器上，在这个服务器上安装证书并信任。
2.然后pc上也安装证书并信任，然后pc上设置代理服务器ip 为 上面部署的服务器ip 端口9080。
3.然后pc 访问 http://服务器ip:9081
4.然后pc上访问某些网址
在第3步打开的网页并不会抓取https的请求，只有http的，这是证书问题吗，还是什么。
大佬，求解~~~感谢~~~~

**Comment by wangborong12345** [comment]
可能你没有把 CA 证书安装到客户端的信任列表？
