### ISSUE TITLE
JetBrains下GoLand编辑器命令行下运行go-mitmproxy后没有安装证书要怎么解决。

### ISSUE THREAD

**Issue by pgdoryoku** [lqqyt2423/go-mitmproxy#49]
有没有手动安装证书的方法，给的https://docs.mitmproxy.org/stable/concepts-certificates/页面里点击http://mitm.it/后直接提示：
If you can see this, traffic is not passing through mitmproxy.
没有安装证书的界面。

**Comment by lqqyt2423** [comment]
证书保存在 ~/.mitmproxy 文件夹中，目前没有通过网络安装证书的功能，请打开文件夹手动安装。
