### ISSUE TITLE
这个应该不属于中间人代理吧

### ISSUE THREAD

**Issue by switch-li** [lqqyt2423/go-mitmproxy#5]
这个应该只是正常的正向代理，应该不是中间人透明代理的模式

**Comment by lqqyt2423** [comment]
是中间人代理

**Comment by switch-li** [comment]
我需要劫持虚拟机内的http/https流量，在服务器上如何部署该工具，以透明的方式代理掉http/https
我尝试了虚拟机ip：192.168.122.xx，代理程序启动监听122网卡8080端口 配置iptables把122这个网卡的80/443流量转发至同以网卡的8080端口，这样配置会有问题吗

**Comment by lqqyt2423** [comment]
对，不是透明代理，仅仅是正向代理实现了中间人
