### ISSUE TITLE
map local json配置文件有具体资料吗

### ISSUE THREAD

**Issue by qiurigao** [lqqyt2423/go-mitmproxy#53]
我想修改指定url path的响应数据。但是map local 的参数无从下手

**Comment by qiurigao** [comment]
写了个配置，但是不起作用
```
{
  "From":{
    "Protocol":"https",
    "Host":"rcsm-cn.realmeservice.com",
    "Method":"POST",
    "Path":"xxx.com/api/tools/login"},
  "To":{
	"Path":"/root/go-mitmproxy/cmd/go-mitmproxy/2"},

	"Enable":true
}
```

**Comment by pepesi** [comment]
可能是这样的
`{
"Items": [{
    "From": ... 
}]
}`

**Comment by qiurigao** [comment]
> 可能是这样的 `{ "Items": [{ "From": ... }] }`

大佬用过吗，可否给个例子

**Comment by pepesi** [comment]
在外面包上 {"Items": [上文你写的item, 可以多个], "Enabled": true}

**Comment by qiurigao** [comment]
load map local error: json: cannot unmarshal string into Go struct field mapFrom.Items.From.Method of type []string
出错了

**Comment by pepesi** [comment]
哦哦，Method 是一个 string array, 改成 ["POST"]

> load map local error: json: cannot unmarshal string into Go struct field mapFrom.Items.From.Method of type []string 出错了
