### ISSUE TITLE
support upstream filter

### ISSUE THREAD

**Issue by pepesi** [lqqyt2423/go-mitmproxy#54]
我正在开发一个addon用来处理特定app的流量，我使用了upstream，由于upstream的带宽和流量限制，我需要过滤流量，只允许特定规则的请求通过upstream访问，其余流量依然从本地发出。

请问有现在有可以实现的办法吗

**Comment by pepesi** [comment]
我暂时添加了UpstreamFilter options方式实现 https://github.com/lqqyt2423/go-mitmproxy/pull/55 ，如果已有现成方案可行，请提醒我

**Comment by lqqyt2423** [comment]
https://github.com/lqqyt2423/go-mitmproxy/blob/v1.7.0/proxy/proxy.go#L393
