### ISSUE TITLE
是否可以支持socks5协议？

### ISSUE THREAD

**Issue by qiurigao** [lqqyt2423/go-mitmproxy#60]

**Comment by lqqyt2423** [comment]
暂不支持

**Comment by zhaozuodong** [comment]
有大佬能解决上游代理的socket代理吗

**Comment by gchuyun** [comment]
+1，希望能支持Http on Socks

**Comment by qiurigao** [comment]
使用方法呢

**Comment by lqqyt2423** [comment]
export https_proxy=socks5://127.0.0.1:7890 http_proxy=socks5://127.0.0.1:7890

**Comment by blackhu** [comment]
`
opts := &proxy.Options{
		Addr:              fmt.Sprintf(":%d", 9080),
		StreamLargeBodies: 1024 * 1024 * 5,
		SslInsecure:       true,
		Debug:             2,
	}
	p, err := proxy.NewProxy(opts)
	p.SetUpstreamProxy(func(req *http.Request) (*url.URL, error) {
		log.Printf("in user config upstream proxy %v %v", req.URL, req.RemoteAddr)
		return url.Parse("socks5://43.131.246.252:33333") //可以
	})
	if err != nil {
		log.Panicln(err)
	}
	defer p.Close()
	log.Panic(p.Start())
	//test:  curl -x "http://127.0.0.1:9080" https://ipv4.icanhazip.com/ -k
`
