### ISSUE TITLE
抓包失败

### ISSUE THREAD

**Issue by ddkwork** [lqqyt2423/go-mitmproxy#7]
您好，测试代码
func baidu() {
	c := httpClient.New()
	c.SetMethod(http.MethodGet)
	c.SetRequestUrl("https://www.baidu.com/")
	c.SetProxy(httpClient.ProtoName.Http(), "127.0.0.1:9080")
	if !c.NewRequest() {
		println(c.Error())
		return
	}
}

返回
|----------------------Error Information-----------------------------|
|    reason:  Get "https://www.baidu.com/": unexpected EOF
|      file:  D:/2k/project/game/vendor/gitee.com/ddkwork/libraryGo/ne
|             gitee.com/ddkwork/libraryGo/net/httpClient/httpClient.go
|      line:  74
|      name:  "gitee.com/ddkwork/libraryGo/net/httpClient.(*object).NewRequest"
|      time:  2021-11-17 16:45:30
| goroutine:  1
|----------------------------End-------------------------------------|

是我哪里设置不对嘛？

**Comment by lqqyt2423** [comment]
这个错误应该是你自己进程的错误，你应该去看代理进程那边的错误

**Comment by ddkwork** [comment]
我把包发到Charles是可以收包的

**Comment by ddkwork** [comment]
换到Linux下可以了，谢谢，Win11再测试下先

**Comment by ddkwork** [comment]
再次请教下如何保存抓包记录？过滤请求体，返回体解码的内容?

**Comment by ddkwork** [comment]
今早再次试了win11.是一样的结果哦

**Comment by ddkwork** [comment]
今晚再次试了下Linux，发现请求体如果是不可见字符的话默认不显示，如何把请求体的hex显示出来呢

**Comment by lqqyt2423** [comment]
你是指前端网页上不可见吗

**Comment by ddkwork** [comment]
> 你是指前端网页上不可见吗

是的

**Comment by lqqyt2423** [comment]
后续会考虑加上这个功能的

**Comment by ddkwork** [comment]
> 后续会考虑加上这个功能的

![Screenshot_20211121_234242_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/142768816-aa155166-6b38-4cc2-a95f-c30688c887fd.jpg)
![Screenshot_20211121_234254_com yandex browser beta](https://user-images.githubusercontent.com/19886504/142768820-3dff9384-e185-4a9b-bf4b-3ae604f10e57.jpg)

报告老师，buffer显示不对啊，当我测试protobuf的时候，另外可以增加protoc解码吗？

**Comment by ddkwork** [comment]
还有就是如果可能的话，建议使用go hex包的hexdump，把hex对应的ASCII也整出来，这些在分析闭源编码的时候有时候很有用喔

**Comment by ddkwork** [comment]
后期再增加pb解码的过滤，那就更加给力了，这些细微的细节太那个了，再导出一波解码接口，可以定义为conten type string,插件开发者输入，已经解码函数，接口签名传这俩个形参，想想都完美啊

**Comment by lqqyt2423** [comment]
你可以自己搞啊，我时间有限
