### ISSUE TITLE
[help] 有一个地方不明白, 请作者帮忙解释下

### ISSUE THREAD

**Issue by timandy** [lqqyt2423/go-mitmproxy#77]
@lqqyt2423 hi, 我对下面这段代码有疑惑, 可以帮忙解答下吗?
[[ ](https://github.com/lqqyt2423/go-mitmproxy/blob/6837f249218ff87f3e16d45ea9ba56148b0b6361/proxy/entry.go#L122-L127)](https://github.com/lqqyt2423/go-mitmproxy/blob/6837f249218ff87f3e16d45ea9ba56148b0b6361/proxy/entry.go#L122-L127)

这个判断条件为什么取反? 不应该是?
```
	// if keep-alive connection close 
 	if c.connCtx.closeAfterResponse { 
 		c.connCtx.ClientConn.Conn.Close() 
 	} 
```

**Comment by lqqyt2423** [comment]
当 `connection: close` 时，就不执行额外的客户端连接关闭的操作，标准库中会在此http结束后执行底层conn close的操作。

否则客户端有可能会收到eof的错误，可以参考这个test。

https://github.com/lqqyt2423/go-mitmproxy/blob/main/proxy/proxy_test.go#L453

**Comment by timandy** [comment]
条件改成反向的有时候测试会失败, 有时候会成功. 测试结果不稳定. 
甚至把条件去掉, 有时候也能成功. 
已经执行过 go clean -testcache

**Comment by timandy** [comment]
保留这个条件, 偶尔会出  expected ServerDisconnected executed before ClientDisconnected, but not 这个结果; 但测试成功率比较高.

**Comment by timandy** [comment]
感谢解答, 基本上明白了意思; 问题关闭了哈

**Comment by lqqyt2423** [comment]
这块确实有点不是很好，当时也是测试好久才有了现在的这个代码，也保持着一直没有动。如果你有更好的解决办法，欢迎协助更改代码。
