### ISSUE TITLE
请问如何再建立了pipe之后，获取用户的来源IP地址

### ISSUE THREAD

**Issue by water007melon** [lqqyt2423/go-mitmproxy#8]
对于HTTPS请求，在通过CONNECT建立pipe之后，后续通过remoteAddr参数获取的远程来源地址都是字符串pipe，如果在这个时候也想获取到来源的IP地址，需要在哪里做一些修改呢？
对于整个代理的工作逻辑还不是很了解，感谢。

**Comment by lqqyt2423** [comment]
后续我会更新的，请持续关注

**Comment by water007melon** [comment]
想了下，在connBuf结构体中增加了客户端来源地址字段，在建立通道的时候，保存了这个信息，后续从pipe拿数据的时候，从这个还原了实际的remotaAddr。功能实现了，不知道这个思路是否合理。

**Comment by lqqyt2423** [comment]
已经支持了，可查看此 commit：https://github.com/lqqyt2423/go-mitmproxy/commit/9f6ef6b320e501a98f6202fd29b4b1b769bb5e0b
