### ISSUE TITLE
Linux部署，出现大量TIME_WAIT

### ISSUE THREAD

**Issue by water007melon** [lqqyt2423/go-mitmproxy#9]
在运行一段时间之后，查看系统网络状态，发现有大量TIME_WAIT等待。
系统参数已经优化配置成这样：
net.ipv4.tcp_syncookies = 1 
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_fin_timeout = 30
依然没有解决。
看起来是和客户端建立的连接没有及时关闭。

**Comment by lqqyt2423** [comment]
代理作为客户端主动关闭连接，出现TIME_WAIT的状态应该是正常的吧。等待60s后这个端口自然就被释放了。端口号那么多，应该不会在这方面出现瓶颈。

**Comment by water007melon** [comment]
我前面没表述清楚：是代理作为服务端和用户客户端建立的连接进入的TIME_WAIT。
未设置参数优化参数之前，运行一段时间之后，ssh直接连接不上，怀疑也是TIME_WAIT过多导致的。

**Comment by lqqyt2423** [comment]
我尝试修复了一下，你拉下最新代码试试

**Comment by lqqyt2423** [comment]
https://github.com/lqqyt2423/go-mitmproxy/releases/tag/v0.1.5

**Comment by water007melon** [comment]
1
